### ISSUE TITLE
程序报错了

### ISSUE THREAD

**Issue by Bell-see** [msgbyte/paw-bilibili-player#2]
在使用的时候报错了 ， 可能是 B 站的政策更新了？
好像项目很久没有维护了😂
```bash
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: `input` must not start with a slash when using `prefixUrl`
    at normalizeArguments (C:\Users\Bell_\Desktop\paw-bilibili-player-master\node_modules\.pnpm\got@11.8.3\node_modules\got\dist\source\core\index.js:484:23)
    at got (C:\Users\Bell_\Desktop\paw-bilibili-player-master\node_modules\.pnpm\got@11.8.3\node_modules\got\dist\source\create.js:112:39)
    at got.stream (C:\Users\Bell_\Desktop\paw-bilibili-player-master\node_modules\.pnpm\got@11.8.3\node_modules\got\dist\source\create.js:221:37)
    at handler (C:\Users\Bell_\Desktop\paw-bilibili-player-master\.next\server\pages\api\proxy\video.js:39:28)
    at Object.apiResolver (C:\Users\Bell_\Desktop\paw-bilibili-player-master\node_modules\.pnpm\next@12.1.6_ef5jwxihqo6n7gxfmzogljlgcm\node_modules\next\dist\server\api-utils\node.js:185:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (C:\Users\Bell_\Desktop\paw-bilibili-player-master\node_modules\.pnpm\next@12.1.6_ef5jwxihqo6n7gxfmzogljlgcm\node_modules\next\dist\server\next-server.js:395:9)
    at async Object.fn (C:\Users\Bell_\Desktop\paw-bilibili-player-master\node_modules\.pnpm\next@12.1.6_ef5jwxihqo6n7gxfmzogljlgcm\node_modules\next\dist\server\base-server.js:496:37)
    at async Router.execute (C:\Users\Bell_\Desktop\paw-bilibili-player-master\node_modules\.pnpm\next@12.1.6_ef5jwxihqo6n7gxfmzogljlgcm\node_modules\next\dist\server\router.js:226:36)
    at async NextNodeServer.run (C:\Users\Bell_\Desktop\paw-bilibili-player-master\node_modules\.pnpm\next@12.1.6_ef5jwxihqo6n7gxfmzogljlgcm\node_modules\next\dist\server\base-server.js:606:29)
```
这是我的版本
```bash
C:\Users\Bell_>node -v
v18.15.0

C:\Users\Bell_>pnpm -v
7.30.0
```
大大加油 为你注册的账号 给你颗 STAR

**Comment by moonrailgun** [comment]
问题已修复。

主要原因:
- b站视频类型统一从flv转为mp4
- b站的真实地址默认是不带协议的(动态协议)，但是请求需要固定协议，现在代理请求固定为https了。
